### ISSUE TITLE
TypeError: reader.skipField is not a function

### ISSUE THREAD

**Issue by TA2k** [protocolbuffers/protobuf-javascript#141]
Since 3.21.1 I receive 
`TypeError: reader.skipField is not a function`

on
`deserializeBinary(data).toObject()`

with 3.21.0 it is working

Node 16.17.1

**Comment by Nihcep** [comment]
Same with 
`reader.readUint64String is not a function`
Working with 3.21.0

**Comment by dibenede** [comment]
This definitely looks like the closure optimizations taking out too much. In the deeper details, all of our tests pass closure deps side, but it looks like our jasmine config for commonjs doesn't include most of our binary/ tests.

**Comment by dibenede** [comment]
I just published a hotfix release (3.21.2) to npm and will close this out now.  Please re-open and ping me if the problem persists.
